FROM python:latest

VOLUME ["/disk"]
RUN apt update && apt install nano htop
RUN mkdir /home/code
RUN git clone https://github.com/benyomin94/israel_bus_info_bot.git /home/code
RUN pip install -r /home/code/requirements.txt

ENTRYPOINT cd /home/code && python3.7 bot.py