FROM python:latest

VOLUME ["/disk"]
RUN apt update && apt install nano htop
RUN pip install celery flower redis
RUN mkdir /home/code
RUN git clone https://github.com/benyomin94/israel_bus_info_bot.git /home/code

ENTRYPOINT cd /home/code && celery -A tasks beat -l warning